sudo: required
dist: trusty

language: cpp

cache:
  directories:
    - $HOME/travisCacheDir

env:
  matrix:
   - BUILD_VERSION=""

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - build-essential
      - cmake
      - devscripts
      - dpatch
      - equivs
      - fakeroot
      - g++-7
      - gcc-7
      - git
      - libappindicator-dev
      - libasound2-dev
      - libdbusmenu-glib-dev
      - liblzma-dev
      - libopus-dev
      - libpulse-dev
      - libssl-dev
      - libunity-dev
      - libva-dev
      - libvdpau-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - xutils-dev
      - yasm

before_install:
  - export CXX="g++-7" CC="gcc-7"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --config gcc
  - g++ --version

before_script:
  - cmake .

script:
  - make -j2
